### ISSUE TITLE
Building Forms

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#108]
## Description
Ability to build a form on the site

As a "manager", <br>
So that "I can build forms", <br>
I want "a form builders"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [ ] Creation of forms
- [ ] Viewing created forms

**Comment by ChaseDitt** [comment]
Wont do this anymore, class did not like it
