### ISSUE TITLE
BUG: Heroku Auto Deployment

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#121]
**Describe the bug:**

heroku auto deployment is having an issue with the runtime.txt and a toml file

**To Reproduce:**

1. Push a PR to main

**Expected behavior:**

should auto deploy to heroku'

**Actual Behavior:**

fails

**Possible Fix**

editing the pyproject.toml

**Comment by smblackwll** [comment]
This issue has been fixed.
