### ISSUE TITLE
{% if user.is_authenticated %} Heroku Bug

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#123]
**Describe the bug:**

Error during template rendering
In template /app/home/templates/base.html, error at line 13

no such table: django_session

**To Reproduce:**

1. Visit the app on Heroku

**Expected behavior:**

Log in verification to work

**Actual Behavior:**

Issue with log in verification

**Screenshots:**

![Image](https://github.com/uiowaSEP2024/003_MAGNA/assets/69732849/38c69840-62f9-474f-ac33-7d69b55c6654)

**Environment:**
Heroku

**Logs**

Include any relevant logs or error messages.

**Possible Fix**

If you have any ideas on how to fix or address the issue, please let us know.

**Comment by smblackwll** [comment]
This issue was not closed properly.
