### ISSUE TITLE
[BUG] Heroku Connection Refused

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#132]
**Describe the bug:**

There is an issue with Heroku and opening a port for sending an email.

**To Reproduce:**
1. Go to Time Off form
2. Fill the form out
3. Click submit

**Expected behavior:**

There should be a page showing successful submission of a form

**Actual Behavior:**

An error appears saying the connection is refused

**Screenshots:**

<img width="490" alt="Screenshot 2024-04-01 at 8 27 48 PM" src="https://github.com/uiowaSEP2024/003_MAGNA/assets/69732849/1bbf9604-117a-482a-a135-5ae783859be7">

**Environment:**
Heroku

**Possible Fix**

Contact Heroku to open a port OR use a third party add on or pluggin

**Comment by smblackwll** [comment]
This issue has been closed.
