### ISSUE TITLE
[BUG] Can't submit an absence request for a single day

### ISSUE THREAD

**Issue by ChaseDitt** [uiowaSEP2024/003_MAGNA#133]
**Describe the bug:**

When trying to submit an absence request with the start date and end date being the same(so just one day off) it throws and error and doesn't submit

**To Reproduce:**

1. Go to 'absence_request page'
2. Click on 'start and end date and set them to the same day'
3. Fill out rest of form and submit

**Expected behavior:**

You should be able to do a single day absence

**Actual Behavior:**

you cant and it throws an error

**Possible Fix**

There must be a check somewhere to verify the form submissions are correct and there must be a check for the end date being after the start date. We could either live it like that and create a second option to do a single day request(not actually different form just a script thing) or just fix the check

**Comment by smblackwll** [comment]
Added [BUG] to the title, changed to grammar stuff
