### ISSUE TITLE
[BUG] Travel auth form 'invalid form submission'

### ISSUE THREAD

**Issue by smblackwll** [uiowaSEP2024/003_MAGNA#145]
**Describe the bug:**

When a user clicks on the travel auth form, a message displaying "invalid form submission" is displayed.

**To Reproduce:**

1. Go to home page
2. Click on travel auth form.
3. See error

**Expected behavior:**

A clear description of what you expected to happen.

**Actual Behavior:**

A clear description of what actually happened.

**Screenshots:**

![image](https://github.com/uiowaSEP2024/003_MAGNA/assets/25370145/acf87616-0be7-4a6a-877b-8a5a1159a4fa)

**Environment:**
 - Heroku Sprint 4 deployment

**Possible Fix**

Make sure the form is not cleaning and submitting when opening.

**Comment by ChaseDitt** [comment]
We have to have the messages in travel_auth so the previous solutions does not work anymore
