### ISSUE TITLE
On Boarding Employees Feature

### ISSUE THREAD

**Issue by teckenrod** [uiowaSEP2024/003_MAGNA#162]
## Description
A page that is accessible by managers, hr, and admin. This page will be a way for new employees to be added into the system. This should include inputs for all fields in the employee class, and on submit, should add a user into the database.

As a "Manager", <br>
So that "I can add a new employee", <br>
I want "To have a place on the kiosk to add an employee to the system"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [ ]  Create HTML page for adding in employee creation form
- [ ]  Add logic to add employee info into database
- [ ]  Make this new page accessible to only hr, manager, and admin.

**Comment by smblackwll** [comment]
So I know this was just opened, but we can probably use Django's built-in registration form, and only allow it to be fillable by HR.
Or, we can re-CSS the admin page so that we can just reuse that page for user creation/deletion
