### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#30]
## Description
_A calendar for HR and Managers to view_

As a "HR person or Manager", <br>
So that "I can see when employees are out", <br>
I want "a calendar"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [ ] _Criteria/Task 1 Calendar updates with employee requests_
- [ ] _Criteria/Task 2 HR/Manager can view calender_
- [ ] _Criteria/Task 3 Calendar shows who is out and when_

**Comment by ChaseDitt** [comment]
The feature is now fully implemented. Will still need to come back to it for regression testing and modifications that we may want to implement later.
