### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#31]
## Description
_Email notifications on requests_

As an "employee", <br>
So that "I know the status of my request", <br>
I want "to receive email updates on my forms"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [ ] _Criteria/Task 1 Employee's receive an email after submitting form_
- [ ] _Criteria/Task 2 Employee's receive an email after approval_
- [ ] _Criteria/Task 3 Employee's receieve an email after denial_

**Comment by smblackwll** [comment]
Looks like django has some built in stuff that could make this a lot easier:
https://docs.djangoproject.com/en/4.2/topics/email/
Leaving this here for future use

**Comment by smblackwll** [comment]
Status and sprint was switched due to not working for every form.
