### ISSUE TITLE
Burn Down Chart

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#37]
## Description
_Burn Down Chart_

As a "developer", <br>
So that "I can predict my team's likelihood of completing their work in the time available", <br>
I want "a burn down chart"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _Criteria/Task 1 Developer can see burn down chart_

**Comment by smblackwll** [comment]
Completed - is in wiki
