### ISSUE TITLE
Heroku Postgres Database

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#38]
## Description
_Heroku Postgres Database_

As a "developer", <br>
So that "I can use a database", <br>
I want "heroku to have a postgres database"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _Criteria/Task 1 Heroku Postgres Database_

**Comment by smblackwll** [comment]
This has been finished with sprint 1 and was left open.
