### ISSUE TITLE
unit test code coverage tool

### ISSUE THREAD

**Issue by teckenrod** [uiowaSEP2024/003_MAGNA#46]
## Description
_Use the following format to name and describe your user stories_

As a "Developer", <br>
So that "I can see how well my code is tested", <br>
I want "See code coverage"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] Code Coverage generated for unit tests
- [x] Files in which coverage is low is outputted
- [x] Lines missing code coverage are made available

**Comment by smblackwll** [comment]
This should have been closed a while ago.
