### ISSUE TITLE
Admin Sign On

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#53]
## Description
Admin Sign On

As an "admin", <br>
So that "I can log in", <br>
I want "to be able to create and log into an admin account"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _Criteria/Task 1 Admin can sign up_
- [x] _Criteria/Task 2 Admin can log in_
- [x] _Criteria/Task 3 Admin can log out_
- [x] _Criteria/Task 4 Admin account access_

**Comment by smblackwll** [comment]
If we do the admin page route, here's the documentation:
https://docs.djangoproject.com/en/4.2/intro/tutorial07/
