### ISSUE TITLE
Manager Sign On

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#54]
## Description
Manager Sign On

As a "manager", <br>
So that "I can log in", <br>
I want "to be able to create and log into an manager account"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _Criteria/Task 1 Manager can sign up_
- [x] _Criteria/Task 2 Manager can log in_
- [x] _Criteria/Task 3 Manager can log out_
- [x] _Criteria/Task 4 Manager account access_

**Comment by smblackwll** [comment]
This has been closed and left open from a while ago.
