### ISSUE TITLE
Seeding Database

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#56]
## Description
Seeded Database

As a "database", <br>
So that "I can query items", <br>
I want "a seeded database"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [ ] _Criteria/Task 1 Admin log In seeded_
- [ ] _Criteria/Task 2 Manager log in seeded_
- [ ] _Criteria/Task 3 HR log in seeded_
- [ ] _Criteria/Task 4 Kiosk log in seeded_

**Comment by smblackwll** [comment]
Some more stuff from the documentation - fixtures looks like the way to seed a database, so not quite as easy as rails
https://docs.djangoproject.com/en/4.2/howto/initial-data/
https://docs.djangoproject.com/en/4.2/topics/db/fixtures/#fixtures-explanation
