### ISSUE TITLE
Absence Forms

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#6]
## Description
_Forms_

As a "user", <br>
So that "I can fill out forms for absence", <br>
I want "be able to click on forms and fill them out to request absence"

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _Criteria/Task 1 User can click on forms for absence_
- [x] _Criteria/Task 2 User can fill out absence forms_
- [x] _Criteria/Task 3 User can submit absence forms_

**Comment by ChaseDitt** [comment]
Exact specifications may be subject to changes per client request or us deciding to change it but the functionality of the form submission is there so I will close this issue and if we need to alter things later I will open a new issue to address that
