### ISSUE TITLE
User Permissions for Admin

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#80]
**Description**  
_As an admin,_  
_so that I can maintain the system,_  
_I want to have administrative permissions._

**Acceptance Criteria**
- [x] Admins can create and manage user accounts.
- [ ] Admins can alter system settings and permissions.
- [ ] Admins can access all system logs and data.

**Comment by smblackwll** [comment]
Added the kiosk sign on branch, since that will merge in the basic Django admin functionality.
