### ISSUE TITLE
Implement New Forms

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#84]
**Description**  
_As an HR professional,_  
_so that I can collect the necessary information from employees,_  
_I want to implement new forms within the system._

**Acceptance Criteria**
- [ ] HR can create and publish new forms within the system.
- [ ] Forms are dynamically created with custom fields as needed.
- [ ] Employees can easily access and submit these new forms.

**Comment by ChaseDitt** [comment]
We have got all the forms that they wished us to implement in the program
