### ISSUE TITLE
View Workflows

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#87]
## Description
_As a user with the necessary permissions,_  
_so that I can monitor the progress and details of workflows,_  
_I want to view all existing workflows._

## Acceptance Criteria:
- [ ] Users can see a list of all workflows.
- [ ] Workflow details are accessible.
- [ ] Permissions are checked to display the workflows.

**Comment by smblackwll** [comment]
Added blocked due to being blocked by: #153
