### ISSUE TITLE
BUG: Heroku Deployment 

### ISSUE THREAD

**Issue by chazwilmot** [uiowaSEP2024/003_MAGNA#95]
**Describe the bug:**

Heroku Deployment is not working due to Python Version and other issues

**To Reproduce:**

1. Deploy to Heroku

**Expected behavior:**

The deploy and build should pass

**Actual Behavior:**

The deploy, build, and GitHub Action fails

**Screenshots:**

remote: -----> Read Python version from poetry.lock        
remote: -----> ^3.11.7 is not valid, please specify an exact Python version (e.g. 3.8.1 or ==3.8.1) in your pyproject.toml (and thus poetry.lock)        
remote:  !     Push rejected, failed to compile Python Poetry app.        
remote: 
remote:  !     Push failed

**Possible Fix**

Change the toml and lock files

**Comment by smblackwll** [comment]
Heroku Deployment is working
